1.	Create a list of 5 integers. Perform and print the result of the following operations: **append, extend, insert, remove, pop, clear, index, count, sort**, and **reverse**.

In [44]:
list = [23,45,13,67,69]
print(list)

[23, 45, 13, 67, 69]


In [45]:
list.append(56)                      # 56 is appended at end of the list
list

[23, 45, 13, 67, 69, 56]

In [46]:
list.extend([100,200,44,66,77])      # Adds all the elements individually at the end
list

[23, 45, 13, 67, 69, 56, 100, 200, 44, 66, 77]

In [47]:
list.insert(1,59)                    # Inserts the elemnt at the specific index
list

[23, 59, 45, 13, 67, 69, 56, 100, 200, 44, 66, 77]

In [48]:
list.remove(23)                      # To remove an element
list

[59, 45, 13, 67, 69, 56, 100, 200, 44, 66, 77]

In [49]:
list.pop()                           # Removes the last element
list

[59, 45, 13, 67, 69, 56, 100, 200, 44, 66]

In [50]:
list.index(45)                       # Returns the index of the element
list

[59, 45, 13, 67, 69, 56, 100, 200, 44, 66]

In [51]:
list.count(67)                       # Returns the count of the element
list

[59, 45, 13, 67, 69, 56, 100, 200, 44, 66]

In [52]:
list.sort()                          # Sorts the list
list

[13, 44, 45, 56, 59, 66, 67, 69, 100, 200]

In [53]:
list.reverse()                       # Reverse the list
list

[200, 100, 69, 67, 66, 59, 56, 45, 44, 13]

In [55]:
list.clear()                         # Clears the list
list

[]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [56]:
student = ("Shubhankar", "Ninad","Yash")

In [57]:
student[1] = "Ajink"

TypeError: 'tuple' object does not support item assignment

In [58]:
# Tuples are immutable. If wanted to change the tuple first convert into list, add the item and reconvert into list

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [59]:
set = {1, 2, 3, 4, 2, 3, 5, 1}
print(set)

{1, 2, 3, 4, 5}


In [61]:
# Sets are implemented using hashing method. So when duplicate comes it checks if it already exist in the set. Only unique elements are there and duplicates are removed automatically

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [66]:
dict = {"name":"Shubhankar","age":22,"city":"Mumbai"}
dict

{'name': 'Shubhankar', 'age': 22, 'city': 'Mumbai'}

In [68]:
dict["age"] = 23
dict["email"] = "john.mckinley@examplepetstore.com"

In [69]:
dict

{'name': 'Shubhankar',
 'age': 23,
 'city': 'Mumbai',
 'email': 'john.mckinley@examplepetstore.com'}

5.	Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [71]:
age = int(input("Enter your age: "))
if age >= 18:
    print("You are eligible to vote")
else:
    print("Not eligible to vote")

Enter your age: 11
Not eligible to vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [73]:
marks = int(input("Enter the marks: "))
if marks >= 90:
    print("A")
elif marks >= 75 and marks <= 89:
    print("B")
elif marks >= 50 and marks <= 74:
    print("C")
else:
    print("Fail")

Enter the marks: 78
B


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [76]:
x = int(input("Enter the number: "))
if x > 0:
    if x%2 == 0:
        print(f"{x} is positive and even")
    else:
        print(f"{x} is positive")
elif x == 0:
    print("Zero")
else:
    print(f"{x} is negative")

Enter the number: 21
21 is positive


## Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [77]:
import numpy as np

In [78]:
arr = np.array(5)

In [82]:
one_dim = np.array([1,2,3,4,5])
one_dim

array([1, 2, 3, 4, 5])

In [86]:
two_dim = np.arange(10,61,10).reshape(2,3)
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [90]:
ran_array = np.random.randint(0,101, size=(4,4))
print(ran_array)

[[ 88   2  47 100]
 [ 22   5  87  64]
 [ 50   2  67  18]
 [ 12  23  46   2]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [93]:
two_dim_array = np.array([[10,20,30],[40,50,60],[70,80,90]])
two_dim_array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [94]:
import pandas as pd

df = pd.DataFrame(two_dim_array, columns=["A","B","C"])
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


## Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [95]:
data = {
    'Name': ['Rahul', 'Amit', 'Sneha', 'Priya', 'Karan',
             'Neha', 'Arjun', 'Riya', 'Rahul', 'Sneha'],
    'Age': [25, 30, 28, 22, 35,
            27, 29, 24, 25, 28],
    'City': ['Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Delhi',
             'Chennai', 'Pune', 'Mumbai', 'Mumbai', 'Pune'],
    'Salary': [50000, 60000, None, 45000, 70000,
               52000, None, 48000, 50000, None]
}

df = pd.DataFrame(data)
print(df)

    Name  Age     City   Salary
0  Rahul   25   Mumbai  50000.0
1   Amit   30    Delhi  60000.0
2  Sneha   28     Pune      NaN
3  Priya   22   Mumbai  45000.0
4  Karan   35    Delhi  70000.0
5   Neha   27  Chennai  52000.0
6  Arjun   29     Pune      NaN
7   Riya   24   Mumbai  48000.0
8  Rahul   25   Mumbai  50000.0
9  Sneha   28     Pune      NaN


In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [98]:
df.describe()

,Age,Salary
count,10.000000,7.000000
mean,27.300000,53571.428571
std,3.653005,8599.557021
min,22.000000,45000.000000
25%,25.000000,49000.000000
50%,27.500000,50000.000000
75%,28.750000,56000.000000
max,35.000000,70000.000000


In [103]:
df[['Name','City']]

,Name,City
0,Rahul,Mumbai
1,Amit,Delhi
2,Sneha,Pune
3,Priya,Mumbai
4,Karan,Delhi
5,Neha,Chennai
6,Arjun,Pune
7,Riya,Mumbai
8,Rahul,Mumbai
9,Sneha,Pune


In [104]:
df.drop('City', axis=1, inplace=True)          # inplace = True means it will change the original data aswell
df

,Name,Age,Salary
0,Rahul,25,50000.0
1,Amit,30,60000.0
2,Sneha,28,NaN
3,Priya,22,45000.0
4,Karan,35,70000.0
5,Neha,27,52000.0
6,Arjun,29,NaN
7,Riya,24,48000.0
8,Rahul,25,50000.0
9,Sneha,28,NaN


In [106]:
df.Salary.fillna(df.Salary.mean(), inplace=True)
df

/tmp/ipython-input-1456066244.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Salary.fillna(df.Salary.mean(), inplace=True)


,Name,Age,Salary
0,Rahul,25,50000.000000
1,Amit,30,60000.000000
2,Sneha,28,53571.428571
3,Priya,22,45000.000000
4,Karan,35,70000.000000
5,Neha,27,52000.000000
6,Arjun,29,53571.428571
7,Riya,24,48000.000000
8,Rahul,25,50000.000000
9,Sneha,28,53571.428571


In [107]:
df.drop_duplicates(inplace=True)
df

,Name,Age,Salary
0,Rahul,25,50000.000000
1,Amit,30,60000.000000
2,Sneha,28,53571.428571
3,Priya,22,45000.000000
4,Karan,35,70000.000000
5,Neha,27,52000.000000
6,Arjun,29,53571.428571
7,Riya,24,48000.000000


In [109]:
!git clone https://github.com/shubhankar233/Data-Science.git



Cloning into 'Data-Science'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 36 (delta 8), reused 28 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (36/36), 9.28 MiB | 11.35 MiB/s, done.
Resolving deltas: 100% (8/8), done.
